[package]
name = "ethashproof-adapter"
version = "0.1.0"
authors = ["Antonio Yang <yanganto@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.69"
actix-web = "2"
actix-rt = "1"
reqwest = { version = "0.10", features = ["json"] }
regex = "1.3.6"
serde_json = "1.0.51"
